# Generated by Django 3.1.3 on 2020-11-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
