# Generated by Django 3.1.3 on 2020-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20201122_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
