# Generated by Django 3.1.3 on 2020-11-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_remove_comment_modify_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_Answer',
        ),
    ]
