# Generated by Django 3.1.3 on 2020-11-26 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0010_delete_comment_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='voter',
            field=models.ManyToManyField(related_name='voter_game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
